### ISSUE TITLE
Problem retrieving user detail fields from v1 API

### ISSUE THREAD

**Issue by Akimkin** [thephpleague/oauth2-linkedin#18]
When retrieving resource owner details information via v1 API, the URL is built as following:
`'https://api.linkedin.com/v1/people/~?format=json&fields='.$fields;`

This doesn't work for me when I try to get such fields as  `email-address` or `positions` - LinkedIn seems to always return default fields like first+last names & headline. I believe correct URL for v1 API should be build like this:
`'https://api.linkedin.com/v1/people/~:('.$fields.')?format=json';`

With this format i am able to get fields I want to request.

**Comment by stevenmaguire** [comment]
@Akimkin thanks for reporting this. I've recently done some work to support both versions of the LinkedIn API and it is likely that this is legitimate.

If you are capable of doing so, I would happily review a pull request with this solution in place.

https://github.com/thephpleague/oauth2-linkedin/blob/c6951350384dc8ad2d9dae1ac92ace6f7ed1b9b9/src/Provider/LinkedIn.php#L100-L111

**Comment by Akimkin** [comment]
@stevenmaguire  Thanks for a quick reply. I'm capable of fixing the source but I'm not sure i can make proper test for my patch.

**Comment by stevenmaguire** [comment]
@Akimkin two test methods already exist that cover the code in question. You should only need to update the tests to match your expected behavior and then get the tests passing. I believe in you!

You'll want to update the following test methods to support your new logic: 

https://github.com/thephpleague/oauth2-linkedin/blob/c6951350384dc8ad2d9dae1ac92ace6f7ed1b9b9/test/src/Provider/LinkedInTest.php#L43-L56

https://github.com/thephpleague/oauth2-linkedin/blob/c6951350384dc8ad2d9dae1ac92ace6f7ed1b9b9/test/src/Provider/LinkedInTest.php#L58-L84

**Comment by stevenmaguire** [comment]
@Akimkin @pwweb @AndreiIgna 

The PR has been merged and a new release has been cut.

https://github.com/thephpleague/oauth2-linkedin/releases/tag/4.1.1
