### ISSUE TITLE
API v1 expiring May 1

### ISSUE THREAD

**Issue by pattmeterson** [thephpleague/oauth2-linkedin#24]
Will there be an update before the end of the month to account for the depreciation of v1 of the LinkedIn API?

**Comment by criticalfault** [comment]
I also would be very interested in an update to V2.

**Comment by stevenmaguire** [comment]
This library

**Comment by stevenmaguire** [comment]
This library is already using the v2 endpoints for OAuth flow and the resource owner method can be configured to use both v1 and v2. 

https://github.com/thephpleague/oauth2-linkedin/tree/4.1.1#resource-owner-endpoint-versions

Did you try this? If so, what specifically are you missing?

**Comment by OJezu** [comment]
I for one, cannot find a way to make it work with v2. I'm trying to get Resource Owner, and getting `not enough permissions to access field summary for GET /me`. I'm requesting `'r_liteprofile', 'r_basicprofile', 'r_emailaddress'` scopes.

**Comment by OJezu** [comment]
So yeah, in V2:
- email has to be fetched in separate request, because go fork yourself
- profile picture has to be fetched in a separate request, because go fork yourself

They decided to make a pretty api, not a functional one. Three requests are needed to obtain Resource Owner information, instead of one. As soon as they disable v1, I guess most of the applications using LinkedIn for sign in will break. There is also no place to discuss this with LinkedIn, as they moved all their support to StackOverflow, and It's not possible to have a discussion there.

**Comment by OJezu** [comment]
Oh, also field names changed, and fields now contain dynamic data based on resource owners preferred and configured locales. Any generic OAuth adapters not trying to understand responses, but just using hardcoded paths will break.

**Comment by Yamakasi** [comment]
Have you been able to manage this or is the known example the working version for the multiple requests ?  If you have a working example it might be nice to add it.

**Comment by stevenmaguire** [comment]
Package version [5.0.0](https://github.com/thephpleague/oauth2-linkedin/releases/tag/5.0.0) is now available with exclusive support for LinkedInAPI v2.
